build_root:
  image_stream_tag:
    cluster: https://api.ci.openshift.org
    name: builder
    namespace: open-cluster-management
    tag: go1.13-linux-amd64
images:
- dockerfile_path: build/Dockerfile-CI
  from: ""
  to: rcm-controller
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
test_binary_build_commands: "true"
tests:
- as: unit
  commands: "true"
  container:
    from: test-bin
zz_generated_metadata:
  branch: prow-test
  org: open-cluster-management
  repo: rcm-controller
